apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database/service.yaml
  - database/statefulset.yaml
  - controller/rbac.yaml
  - controller/deployment.yaml
  - controller/service.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/ingressroute.yaml
